
services:
  postgres:
    image:  ${DB_IMAGE_NAME:-postgres:17.2-alpine}  # Usa la imagen oficial de PostgreSQL
    container_name: ${DB_CONTAINER_NAME:-postgres}
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-default_user}  # Usuario con valor por defecto
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-default_password}  # Contraseña por defecto
      POSTGRES_DB: ${POSTGRES_DB:-default_db}  # Base de datos por defecto
      TZ: ${TZ:-UTC}  # Zona horaria con valor predeterminado
    ports:
      - "5432:5432"  # Expone el puerto 5432 del contenedor al host
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Volumen persistente para los datos
      - ./initdb.d:/docker-entrypoint-initdb.d/  # Scripts de inicialización
    command: >
      postgres -c custom.database_name=${POSTGRES_DB}
               -c custom.user_name=${POSTGRES_USER}
               -c custom.user_password=${POSTGRES_PASSWORD}
    networks:
      - postgres_network  # Red personalizada
    restart: unless-stopped  # Reinicia el contenedor en caso de fallo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-default_user} -d ${POSTGRES_DB:-default_db} || exit 1"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
    logging:
      driver: "json-file"  # Usa logging JSON por defecto
    env_file:
      - .env  # Archivo de variables de entorno

volumes:
  postgres_data:
    driver: local

networks:
  postgres_network:
    driver: bridge
